### ISSUE TITLE
Need more setup info

### ISSUE THREAD

**Issue by yannba** [JJones780/tabloro#2]
Hi JJones,
Thank you for your Tabloro fork and improvement! It's exactly what we need in the time of self-isolation. Self-hosting the storage of the assets was a great thing to do.

However, it's not completely clear for me how to set it up. I have very basic server admin skills. I have my own VPS with Ubuntu 18, Apache, and my domain name attached and https enabled with lets-encrypt. Installing Node.js and MongoDB doesn't seem to be a problem. 

Then I have a few questions:
1) To which directory on my server should I copy the Tabloro files from your repository?
2) How do I make it work with my domain name (e.g. https://mydomain.name/tabloro)? Should I put something in `/var/www`, or set up something in Apache?
3) Do I need additional certificate from lets-encrypt if I already have one for mydomain.name?
4) What are the server requirements? I have 1 VCPU, 2 GB RAM, 20 GB disk - should that be enough?

Thank you very much for your help!

**Comment by JJones780** [comment]
Hi Yannba,

1)  You can put it in any directory you want... 'npm start' from the tabloro top directory  serves the website itself. No need for Apache, NGINX etc.   I use the screen command to leave it running on my server and reconnect when I log on. It should really be run as a service ( which would restart etc ).

2) You'll have to change the code in tabloro/server.js to point to your https certificates. You can change the ports etc there too. Note the express server lines (  but note that the express http server simply rediercts to https ).
When running locally for testing etc you'll need to set up a localhost certificate and instruct firefox, Chrome etc to trust it. See  https://github.com/FiloSottile/mkcert
Note, the videoconferencing isn't yet working... so I feel a bit guilty leaving the webRTC requirements in there without looking at it further.

3) Nope.. unless you are using a subdomain not covered by your certificate.

4) That should easily suffice for friends and family.. maybe many more?

Your welcome. Sorry I didn't see this sooner.
