### ISSUE TITLE
Not working - seems to be a problem with IPv6

### ISSUE THREAD

**Issue by yannba** [JJones780/tabloro#4]
This is what I get after `npm start`:
```
`> Tabloro@4.0.0 start /var/www/tabloro
> NODE_PATH=./config:./app/controllers:./lib NODE_ENV=development ./node_modules/.bin/nodemon server.js

8 Apr 20:52:58 - [nodemon] v1.2.1
8 Apr 20:52:58 - [nodemon] to restart at any time, enter `rs`
8 Apr 20:52:58 - [nodemon] watching: *.*
8 Apr 20:52:58 - [nodemon] starting `node --harmony server.js`
development
/!\  EurecaServer syntax is deprecated please see http://eureca.io/doc/tutorial-A00-Deprecations.html
* using primus:engine.io
attach eurecaServer 0.6.0-dev
the server/replset/mongos/db options are deprecated, all their options are supported at the top level of the options object [poolSize,ssl,sslValidate,sslCA,sslCert,sslKey,sslPass,sslCRL,autoReconnect,noDelay,keepAlive,keepAliveInitialDelay,connectTimeoutMS,family,socketTimeoutMS,reconnectTries,reconnectInterval,ha,haInterval,replicaSet,secondaryAcceptableLatencyMS,acceptableLatencyMS,connectWithNoPrimary,authSource,w,wtimeout,j,forceServerObjectId,serializeFunctions,ignoreUndefined,raw,bufferMaxEntries,readPreference,pkFactory,promiseLibrary,readConcern,maxStalenessSeconds,loggerLevel,logger,promoteValues,promoteBuffers,promoteLongs,domainsEnabled,checkServerIdentity,validateOptions,appname,auth,user,password,authMechanism,compression,fsync,readPreferenceTags,numberOfRetries,auto_reconnect,minSize,monitorCommands,retryWrites,retryReads,useNewUrlParser,useUnifiedTopology,serverSelectionTimeoutMS,useRecoveryToken,autoEncryption]
eurecaServer config
Express https app started on port 4000
{ address: '::', family: 'IPv6', port: 4000 }
(node:15815) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
(node:15815) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
(node:15815) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
(node:15815) DeprecationWarning: Mongoose: the `isAsync` option for custom validators is deprecated. Make your async validators return a promise instead: https://mongoosejs.com/docs/validation.html#async-custom-validators
(node:15815) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.
```

How do I connect to Tabloro in browser? I tried [my_IP]:4000 (and also :3000), it doesn't work.

**Comment by JJones780** [comment]
You can connect via:   https://localhost:4000
The errors you get are the same as I see... but things work quite well.

HTTPS Certificate:
WebRTC ( for the video chat) now requires https... which requires a certificate.
For a server on the web you can use letsencrypt.
For your test machine you'll need to make a self-signed certificate for localhost.
This looks easier than the way I did it:  https://github.com/FiloSottile/mkcert

Alternatively,  you can dive into the code and change the server back to http since the webrtc stuff isn't yet working anyways.

Sorry I didn't see your comment earlier.

**Comment by yannba** [comment]
Hi,

Thank you for your replies anyway, I hope it may be useful for someone else. 

In the meantime, I forked the project and made it work with the help of my friends. However, it's still buggy, and playing with it is quite hard. It seems to need massive work on it, which no one yet is able to afford (software developers, unlike many others, do not get more free time during the pandemics).

Anyway, thank you for lifting it up and sharing it, it was worth a try!

**Comment by JJones780** [comment]
The original author put his site back online and I was hoping he would update it but that doesn't seem to have happened.  My simpleserver branch is working well for me. There are still issues with touch interface scale issues and the video chat doesn't work.  Maybe I'll find time to work on it again... but I keep hoping we don't need it anymore.
